baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 1
  # Show reading time in minutes for posts
  showReadingTime = false

[languages]
  [languages.en]
    title = "jpk"
    subtitle = "website"
    keywords = ""
    copyright = "---"
    menuMore = "more"
    writtenBy = "written by"
    readMore = "read more"
    readOtherPosts = "read other posts"
    newerPosts = "newer posts"
    olderPosts = "older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "jason p kovalski"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "fitness"
        name = "fitness"
        url = "/fitness"
      [[languages.en.menu.main]]
        identifier = "gaming"
        name = "gaming"
        url = "/gaming"
      [[languages.en.menu.main]]
        identifier = "gear"
        name = "gear"
        url = "/gear"
      [[languages.en.menu.main]]
        identifier = "programming"
        name = "programming"
        url = "/programming"